// Mock data for demo mode
// This data is used when no Supabase credentials are configured

export const mockOperators = [
  {
    id: "op-001",
    operator: "Golden Crown Casino",
    contact_name: "Sarah Johnson",
    market: "United Kingdom",
    language: "English",
    contact_email: "sarah.j@goldencrown.example",
    tags: ["VIP", "High Volume"],
    engagement_status: "hot",
    pref_comm: "email",
    created_at: "2024-01-15T10:30:00Z",
    updated_at: "2024-03-20T14:22:00Z",
  },
  {
    id: "op-002",
    operator: "Lucky Star Gaming",
    contact_name: "Marcus Chen",
    market: "Malta",
    language: "English",
    contact_email: "m.chen@luckystar.example",
    tags: ["New Partner"],
    engagement_status: "medium",
    pref_comm: "phone",
    created_at: "2024-02-01T09:15:00Z",
    updated_at: "2024-03-18T11:45:00Z",
  },
  {
    id: "op-003",
    operator: "Atlantic Slots",
    contact_name: "Emma Williams",
    market: "Germany",
    language: "German",
    contact_email: "e.williams@atlanticslots.example",
    tags: ["Premium"],
    engagement_status: "hot",
    pref_comm: "email",
    created_at: "2024-01-20T08:00:00Z",
    updated_at: "2024-03-19T16:30:00Z",
  },
  {
    id: "op-004",
    operator: "Nordic Bet",
    contact_name: "Lars Eriksson",
    market: "Sweden",
    language: "Swedish",
    contact_email: "lars@nordicbet.example",
    tags: ["Sports Focus"],
    engagement_status: "cold",
    pref_comm: "email",
    created_at: "2024-02-10T12:00:00Z",
    updated_at: "2024-03-10T09:15:00Z",
  },
]

export const mockIncentives = [
  {
    id: "inc-001",
    name: "Welcome Bonus 100%",
    description: "100% match bonus up to $500 for new players",
    incentive_keywords: ["welcome", "match", "bonus"],
    tags: ["Acquisition"],
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "inc-002",
    name: "Free Spins Friday",
    description: "50 free spins every Friday on selected slots",
    incentive_keywords: ["free spins", "friday", "slots"],
    tags: ["Retention"],
    created_at: "2024-01-05T00:00:00Z",
  },
  {
    id: "inc-003",
    name: "VIP Cashback",
    description: "10% weekly cashback for VIP members",
    incentive_keywords: ["cashback", "vip", "weekly"],
    tags: ["VIP", "Retention"],
    created_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "inc-004",
    name: "Reload Bonus",
    description: "50% reload bonus every Monday",
    incentive_keywords: ["reload", "monday", "bonus"],
    tags: ["Retention"],
    created_at: "2024-01-15T00:00:00Z",
  },
]

export const mockCampaigns = [
  {
    id: "camp-001",
    ref: "CAMP-GOLD-WELC-123456",
    operator: "Golden Crown Casino",
    incentive: "Welcome Bonus 100%",
    start_date: "2024-03-01",
    end_date: "2024-03-31",
    status: "active",
    tags_incentive: ["Acquisition"],
    created_at: "2024-02-25T10:00:00Z",
  },
  {
    id: "camp-002",
    ref: "CAMP-LUCK-FREE-234567",
    operator: "Lucky Star Gaming",
    incentive: "Free Spins Friday",
    start_date: "2024-03-15",
    end_date: "2024-04-15",
    status: "active",
    tags_incentive: ["Retention"],
    created_at: "2024-03-10T14:30:00Z",
  },
  {
    id: "camp-003",
    ref: "CAMP-ATLA-VIP-345678",
    operator: "Atlantic Slots",
    incentive: "VIP Cashback",
    start_date: "2024-04-01",
    end_date: "2024-06-30",
    status: "planned",
    tags_incentive: ["VIP", "Retention"],
    created_at: "2024-03-20T09:00:00Z",
  },
]

export const mockEmails = [
  {
    email_id: "GOLWEL123456",
    status: "approved",
    reply_status: "Replied",
    operator: "Golden Crown Casino",
    incentive: "Welcome Bonus 100%",
    created_time: "2024-03-15T10:30:00Z",
    ai_answered: true,
    generated_email_subject: "Exclusive Welcome Bonus Partnership Opportunity",
    generated_email_body:
      "Dear Sarah,\n\nI hope this email finds you well. I wanted to reach out regarding an exciting partnership opportunity...",
    final_email_subject: "Exclusive Welcome Bonus Partnership - Golden Crown",
    final_email_body:
      "Dear Sarah,\n\nI hope this email finds you well. Following our previous discussion, I'm delighted to present...",
    follow_up_1: true,
    follow_up_2: false,
    pref_comm: "email",
  },
  {
    email_id: "LUCFRE234567",
    status: "pending_review",
    reply_status: "No Reply",
    operator: "Lucky Star Gaming",
    incentive: "Free Spins Friday",
    created_time: "2024-03-18T14:45:00Z",
    ai_answered: true,
    generated_email_subject: "Free Spins Friday Campaign Proposal",
    generated_email_body:
      "Dear Marcus,\n\nI'm reaching out to discuss a potential Free Spins campaign that could significantly boost player engagement...",
    final_email_subject: "",
    final_email_body: "",
    follow_up_1: false,
    follow_up_2: false,
    pref_comm: "phone",
  },
  {
    email_id: "ATLVIP345678",
    status: "sent",
    reply_status: "Pending",
    operator: "Atlantic Slots",
    incentive: "VIP Cashback",
    created_time: "2024-03-19T09:15:00Z",
    ai_answered: true,
    generated_email_subject: "VIP Cashback Program - Partnership Discussion",
    generated_email_body:
      "Dear Emma,\n\nI wanted to follow up on our VIP Cashback program proposal that I believe would be perfect for Atlantic Slots...",
    final_email_subject: "VIP Cashback Program - Atlantic Slots Partnership",
    final_email_body:
      "Dear Emma,\n\nThank you for your continued interest in our partnership. I'm excited to present our VIP Cashback program...",
    follow_up_1: true,
    follow_up_2: true,
    pref_comm: "email",
  },
]

export const mockCalibration = {
  greeting: "warm",
  follow_up: "persistent",
  excitement: "enthusiastic",
  tone: "professional",
  completed_at: "2024-03-01T10:00:00Z",
}
